baseURL: https://nsddd.top
languageCode: en-us
DefaultContentLanguage: en-us
title: cubxxw is blog
theme: PaperMod

# Config WIKI
# https://github.com/adityatelange/hugo-PaperMod/wiki/Variables
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
googleAnalytics: UA-123-45
pygmentsUseClasses: true
minify:
  disableXML: true
  minifyOutput: true
params:
  env: production
  title: ExampleSite
  description: ExampleSite description
  keywords:
    - Blog
    - CloudNative
    - cubxxw
  author: Me
  images:
    - <link or path of image for opengraph, twitter-cards>
  DateFormat: January 2, 2006
  # defaultTheme: light
  # defaultTheme: dark
  defaultTheme: auto # to switch between dark or light according to browser theme
  disableThemeToggle: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowFullTextinRSS: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true
  assets:
    favicon: <link / abs url>
    favicon16x16: <link / abs url>
    favicon32x32: <link / abs url>
    apple_touch_icon: <link / abs url>
    safari_pinned_tab: <link / abs url>
  label:
    text: Home
    icon: /apple-touch-icon.png
    iconHeight: 35
  profileMode:
    # Enabled or not
    enabled: true
    title: Hi there 👋
    subtitle: |
      My name is Xinwei(bear) Xiong 🤖. My loyalty is to adventure ☀️,
      I'm a big open source fan Ⓜ️. I have a big dream and will realize it next year.
    imageUrl: ../assets/cubxxw-image.jpg
    imageWidth: 120
    imageHeight: 120
    # imageTitle: My name is bear
    buttons:
      - name: Posts
        url: posts
      - name: archives
        url: archives
      - name: Tags
        url: tags
  homeInfoParams:
    Title: Hi there 👋
    Content: My name is Xinwei(bear) Xiong. My loyalty is to adventure 🤖
  socialIcons:
    - name: rss
      url: https://nsddd.top/index.xml
    - name: twitter
      url: https://twitter.com/xxw3293172751
    - name: stackoverflow
      url: https://stackoverflow.com/users/17393425/xinwei-xiong
    - name: github
      url: https://github.com/cubxxw
    - name: zhihu
      url: https://www.zhihu.com/people/3293172751
    - name: linkedin
      url: https://www.linkedin.com/in/cubxxw
    - name: facebook
      url: https://www.facebook.com/profile.php?id=100034435372354
    - name: bilibili
      url: https://space.bilibili.com/1233089591
    - name: youtube
      url: https://https//www.youtube.com/channel/UCd3qbRbMwYlh5uKneo_2m_w
    - name: liberapay
      url: https://liberapay.com/xiongxinwei/donate
    - name: kofi
      url: https://ko-fi.com/cubxxw
    - name: email
      url: https://mail.google.com/mail/u/0/?fs=1&tf=cm&to=3293172751nss@gmail.com
    - name: weibo
      url: https://weibo.com/u/6248930985
  ShareButtons: ["linkedin", "twitter","bilibili","zhihu","email","facebook"] # To customize which share buttons to be enabled on page
  analytics:
    google:
      SiteVerificationTag: XYZabc
    bing:
      SiteVerificationTag: XYZabc
    yandex:
      SiteVerificationTag: XYZabc
  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true
  editPost:
    URL: https://github.com/<path_to_repo>/content
    Text: Suggest Changes
    appendFilePath: true
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys:
      - title
      - permalink
      - summary
      - content
menu:
  main:
    - identifier: lint
      name: 🤸About me
      url: https://nsddd.top
      weight: 10
    - identifier: categories
      name: 🗂️Categories
      url: /categories/
      weight: 20
    - identifier: tags
      name: 🏷️Tags
      url: /tags/
      weight: 30
    - identifier:
      name: 🔍Search
      url: /search/
      weight: 40
    - identifier: 
      name: Ⓜ️Github
      url: https://github.com/cubxxw/blog
      weight: 50
markup:
  highlight:
    noClasses: false
outputs:
    home:
      - HTML
      - RSS
      - JSON # is necessary